# Generated by Django 6.0.2 on 2026-02-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Business description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Business creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Business last update timestamp')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this user account is active'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.business'),
        ),
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business this user belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.business'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'business')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business'], name='core_produc_busines_13a014_idx'),
        ),
    ]
